FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    paho-mqtt==1.6.1 \
    psycopg2-binary==2.9.9 \
    fastapi==0.104.1 \
    uvicorn[standard]==0.24.0 \
    websockets==12.0

COPY ../backend/ .

CMD ["python", "main.py"]
